name: chat_v1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  llamadart: ^0.6.4
  flutter_markdown: ^0.7.3
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  provider: ^6.1.2
  sqflite: ^2.0.0
  path: ^1.8.0
  shared_preferences: ^2.5.5
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/models/qwen306.gguf
   - assets/animations/typing.json
   - assets/images/cheetah.png


hooks:
  user_defines:
    llamadart:
      llamadart_native_backends:
        platforms:
          android-arm64:
            backends: [cpu]
            cpu_profile: full 